server {
    server_name app.stco.cloud;
    location / {
        #auth_basic "STCO DEV APP";
        #auth_basic_user_file /home/ubuntu/.htpasswd;
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_buffering off;
    }

    listen 80;
}
